### ISSUE TITLE
Use importlib for plugin support instead of custom implementation 

### ISSUE THREAD

**Issue by Spacecow99** [chris2727/BeastBot#5]
I know we wanted to do some sort of plugin support like willie has so extending the bots functionality is easier and that I said I was going to write a package to do it but python2.7 has a basic importlib implementation that could speed up development and if any custom functionality has to be implemented then we can just write a subclass for it.  https://docs.python.org/2.7/library/importlib.html

**Comment by chris2727** [comment]
Made if modular. Didnt use importlib, but it works.
